apiVersion: v1
kind: Service
metadata:
  name: assistente-local
  labels:
    app: assistente-local
spec:
  type: ClusterIP
  selector:
    app: assistente-local
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: metrics
      port: 8001
      targetPort: 8001
